{% set name = "pe-configurator" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0fb40775f837e629f4597c429d3b1d7a1415b4a0ad4f3138564d150f5f42c0d3

build:
  entry_points:
    - peconfigurator = peconfigurator.proc_samples:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=3.4.3
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - asimov >=0.4.0
    - lalsuite >=7.14
    - pandas
    - pesummary >=1.0.2
    - nbformat
    - bilby
    - jupyter
    - nbconvert
test:
  imports:
    - peconfigurator
  commands:
    - pip check
    - peconfigurator --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pe-configurator/
  summary: Tools to identify waveform settings and prior bounds for gravitational wave parameter estimation.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - transientlunatic
    - mj-will
